### PR TITLE
Schedule

### PR DESCRIPTION
**Pull request by nzambello**
Added content and styles for `/schedule` page with agenda by day and track.
Added relative links in talks page and in header.

### CODE REVIEW

**Comment by nzambello** [comment]
I've mocked start times for tallks with current time, until we have scheduled entirely talks and they have dates in the content

**Comment by nzambello** [comment]
Mancano anche gli stili per mobile

**Comment by giuliaghisini** [comment]
è normale che gli orari non siano tutti mescolati?

**Comment by nzambello** [comment]
> is it normal that talks are not ordered by time?
Nope, but I discovered it happens on Chrome, while on Firefox and Safari they are ordered by start time.

It's a bit strange, because talks are rendered from an array sorted by date as ```[].sort()```

**Comment by nzambello** [comment]
Notes from @nekorin:
```se possibile metterei il nome dello speaker prima del testo un po' più piccolo (so che nell'esempio era come l'hai fatto, ma vederlo lontano dalla foto mi disturba)
ultimo: servirà indicare l'ora di inizio + l'ora di fine oppure la durata visto che ci sono talk da 20' o da 40' (così l'utente non deve fare i conti)
```

**Comment by giuliaghisini** [comment]
> > is it normal that talks are not ordered by time?
> > Nope, but I discovered it happens on Chrome, while on Firefox and Safari they are ordered by start time.
> 
> It's a bit strange, because talks are rendered from an array sorted by date as `[].sort()`

solved! The problem was on sort function on the array. The compairson between two dates like a > b returns true/false (boolean value) but sort needs negative, zero or positive value. So the solution's return a > b ? 1:-1

**Comment by giuliaghisini** [comment]
> Notes from @nekorina:
> 
> > se possibile metterei il nome dello speaker prima del testo un po' più piccolo (so che nell'esempio era come l'hai fatto, ma vederlo lontano dalla foto mi disturba)
> > ultimo: servirà indicare l'ora di inizio + l'ora di fine oppure la durata visto che ci sono talk da 20' o da 40' (così l'utente non deve fare i conti)
> 
> \cc @pnicolli @giuliaghisini

done

**Comment by giuliaghisini** [comment]
@nzambello ho sisteamato un po di cose, c'è altro da fare?

**Comment by nzambello** [comment]
Now it's ok and complete, it's responsive and has any of infos we wanted to show. 

Before merging we have to check our time slots for breaks and other things which are hard coded in schedule lists.
\cc @pnicolli @giuliaghisini

**Pull request merged**
